src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields:['email'], message: "Un autre utilisateur possède déjà cette adresse e-mail, merci de la modifier")]
#[ORM\HasLifecycleCallbacks]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    #[Assert\Email(message: "Veuillez renseigner une adresse e-mail valide")]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    #[Assert\NotBlank(message:"Le mot de passe ne peut pas être vide")]
    #[Assert\Length(min: 8, minMessage:"Le mot de passe doit contenir au moins {{ limit }} caractères")]
    #[Assert\Regex(pattern:'/[A-Z]/', message:"Le mot de passe doit contenir au moins une majuscule")]
    #[Assert\Regex(pattern:'/[a-z]/', message:"Le mot de passe doit contenir au moins une minuscle")]
    #[Assert\Regex(pattern: '/\d/', message: "Le mot de passe doit contenir au moins un chiffre")]
    #[Assert\Regex(pattern: '/[^A-Za-z0-9]/', message: "Le mot de passe doit contenir au moins un caractère spécial")]
    private ?string $password = null;

    #[Assert\EqualTo(propertyPath:"password", message:"Vous n'avez pas correctement confirmé votre mot de passe")]
    public ?string $passwordConfirm = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Vous devez renseigner votre prénom")]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Vous devez renseigner votre nom de famiile")]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message:"Vous devez renseigner une image de profil")]
    #[Assert\File(maxSize:"2M", maxSizeMessage:"La taille du fichier est trop grande")]
    #[Assert\Image(mimeTypes:["image/jpeg", "image/jpg", "image/png"], mimeTypesMessage:"Le format de l'image n'est pas valide")]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 10, minMessage:"Votre description doit faire plus de 10 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 10, max: 255, minMessage:"Votre introduction doit faire plus de 10 caractères", maxMessage: "Votre introduction ne doit pas dépasser plus de 255 caractères")]
    private ?string $introduction = null;

    /**
     * Complète automatiquement le slug pour les nouveaux utilisateurs lors d'une inscription
     *
     * @return void
     */
    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName." ".$this->lastName." ".uniqid());
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        //donne le rôle USER à tous les utilisatuers
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): static
    {
        $this->introduction = $introduction;

        return $this;
    }
}

templates/partials/footer.html.twig
<footer class="footer bg-primary py-5 mt-5 text-white text-center">
    &copy; Copyright EPSE - Symfony 7.3
</footer>

templates/partials/header.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path('homepage') }}">AutoGar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">

                <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}">Accueil</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ path('all_auto') }}">Nos voitures</a>
                </li>

            </ul>
            <ul class="navbar-nav ms-auto">
                {% if app.user %}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" id="accountDropdownLink">{{ app.user.fullName }}</a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="accountDropdownLink">
                            {% if is_granted("ROLE_ADMIN") %}
                                <a href="{{path('add_auto')}}" class="dropdown-item">Ajouter un véhicule</a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a href="{{path('account_index')}}" class="dropdown-item">Mon compte</a>
                            <a href="{{ path('account_update') }}" class="dropdown-item">Modifier mon profil</a>
                            <div class="dropdown-divider"></div>
                            <a href="{{ path('account_logout') }}" class="dropdown-item">Déconnexion</a>
                        </div>
                    </li>   
                {% else %}
                    <li class="nav-item">
                    <a href="{{path('account_register')}}" class="nav-link">Inscription</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{path('account_login')}}" class="nav-link">Connexion</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% for label, messages in app.flashes %}
    <div class="container">
        <div class="alert alert-{{ label }}">
        {% for message in messages %}
            <p>{{ message | raw }}</p>
        {% endfor %}</div>
    </div>
{% endfor %}